name: Mirror Upstream Citron

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:   

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: sync citron mirror
        run: |
          git clone --bare https://github.com/pflyly/citron-mirror.git mirror.git
          cd mirror.git
          git remote add upstream https://git.citron-emu.org/citron/emu.git
          git fetch upstream
          git update-ref refs/heads/master refs/remotes/upstream/master
          git push --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pflyly/citron-mirror.git
