name: Mirror Upstream

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:   

jobs:
  citron:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: sync citron mirror
        run: |
          git clone --bare https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/citron-mirror.git citron.git
          cd citron.git
          git remote add upstream https://git.citron-emu.org/citron/emu.git
          git fetch upstream
          git update-ref refs/heads/master refs/remotes/upstream/master
          git push --mirror https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/citron-mirror.git
  
  torzu:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: sync torzu mirror
        run: |
          git clone --bare https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/torzu-mirror.git torzu.git
          cd torzu.git
          git remote add upstream https://notabug.org/litucks/torzu.git
          git fetch upstream
          git update-ref refs/heads/main refs/remotes/upstream/master
          git push --mirror https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/torzu-mirror.git

  eden:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: sync eden mirror
        run: |
            git clone --mirror https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/eden-mirror.git
            cd eden-mirror.git
            git remote add upstream https://git.eden-emu.dev/eden-emu/eden.git
            git fetch upstream --prune
            
            for ref in $(git for-each-ref --format='%(refname:strip=2)' refs/heads/); do
                git update-ref -d "refs/heads/$ref"
            done

            for ref in $(git for-each-ref --format='%(refname:strip=3)' refs/remotes/upstream/); do
                if [[ "$ref" != "HEAD" ]]; then
                git update-ref "refs/heads/$ref" "refs/remotes/upstream/$ref"
                fi
            done

            git push --mirror
