name: Mirror Upstream

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:   

jobs:
  citron:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: sync citron mirror
        run: |
          git clone --bare https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/citron-mirror.git citron.git
          cd citron.git
          git remote add upstream https://git.citron-emu.org/citron/emu.git
          git fetch upstream
          git update-ref refs/heads/master refs/remotes/upstream/master
          git push --mirror https://x-access-token:${{ secrets.GH_PAT }}@github.com/pflyly/citron-mirror.git
  
  torzu:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: sync citron mirror
        run: |
          git clone --bare https://x-access-token:${{ secrets.GH_PAT }}@github.com:pflyly/torzu-mirror.git torzu.git
          cd torzu.git
          git remote add upstream https://notabug.org/litucks/torzu.git
          git fetch upstream
          git update-ref refs/heads/main refs/remotes/upstream/master
          git push --mirror https://x-access-token:${{ secrets.GH_PAT }}@github.com:pflyly/torzu-mirror.git
